### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by Alexx221x** [Rai220/RnnChatPrediction#1]
Создал собственный датасет с переписок,
Общее количество символов: 3534
Уникальных символов: 58
После компиляции модели, при попытке обучить 

> `(history= model.fit(dataset.repeat(), epochs=5, steps_per_epoch=steps_per_epoch, callbacks=[checkpoint_callback])` )

Выводит ошибку: list index out of range. 
Код скопирован один в один, вместе с обработкой самого json из телеграмм

Прошу помочь, т.к. не понимаю в чем проблема. Много нервов на это убил(

**Comment by Rai220** [comment]
> Выводит ошибку: list index out of range.

Киньте полный текст ошибки, а лучше ссылку на весь проект, где она возникает - попробую посмотреть, в чем проблема.
